SHELL := /bin/bash

## Inherit targets from another Makefile
%:
	make -f ../../../shared/makefiles/SLSMakefile $@

## CI TARGETS

test-module:
	echo "No tests"

lint-module:
	echo "Nothing to lint"

build-module:
	echo "No lib build defined for this sls module"

# DEVELOPER TARGETS
# Developers can add custom targets below at will

