name: breda-pr-deploy

on:
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    name: Deploy PR environment
    uses: flaviostutz/gh-makefile/.github/workflows/make-ci.yml@main
    with:
      working-directory: ./modules/breda-jazz-festival/breda-ui
      tooling: node
      tooling-version: 16
      stage: pr${{ github.event.number }}
      target-build: true
      target-lint: true
      target-unit-tests: true
      target-deploy: true
      environment: pr
      AWS_DEFAULT_REGION: us-east-1
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  # e2e-tests:
  #   name: E2E tests
  #   uses: flaviostutz/gh-makefile/.github/workflows/make-ci.yml@main
  #   with:
  #     working-directory: ./
  #     stage: pr${{ github.event.number }}
  #     target-build: true
  #     target-integration-tests: true
  #     # environment-url: ${{ needs.deploy.outputs.environment-url }}
  #   needs: deploy
